### ISSUE TITLE
Implement `behat --init @<module>`

### ISSUE THREAD

**Issue by chillu** [silverstripe-labs/silverstripe-behat-extension#1]
See https://github.com/Behat/Symfony2Extension/blob/master/src/Behat/Symfony2Extension/Console/Processor/InitProcessor.php

**Comment by phptek** [comment]
I think this can be closed can it not? (If for no other reason other than its being 5 years old, I just init'd my folder hierarchy ala (using 1.0.3)

```
./vendor/bin/behat --init @app
```
