### ISSUE TITLE
Can't connect to DB and not deleting tmp database

### ISSUE THREAD

**Issue by trev** [silverstripe-labs/silverstripe-behat-extension#115]
I'm hoping you can give me a hand here, see if I'm missing something. I'm using this with SS 3.1.

When I visit any page in a scenario (i.e: `Given I am on "/Security/login"`) I get
> Fatal error: DB::connect: Not passed a valid database config in /var/www/someproject.dev/framework/model/DB.php on line 168

Also, when I checkout MySQL the temp database never gets cleaned up. So I have a bunch of `ss_tmpdb.....` DBs.

Any guidance would be greatly appreciated.

**Comment by trev** [comment]
I've debugged this some more and it seems that at this point https://github.com/silverstripe-labs/silverstripe-testsession/blob/master/code/TestSessionEnvironment.php#L173 `$databaseConfig` is totally fine during the setup phases where the tmp database is created an so on. It holds a valid database config such as:
    
    (
        [type] => MySQLDatabase
        [server] => 192.168.33.10
        [username] => mysite
        [password] => mysite
        [database] => ss_tmpdb9341791
        [timezone] => +0:00
    )

However as soon as a step is ran such as:
    
    Scenario: Login to MySites            # xebidyconnect/tests/behat/features/Login.feature:3
        Given I am on "/Security/login"     # Xebidyconnect\Test\Behaviour\FeatureContext::visit()

The value of `$databaseConfig

**Comment by trev** [comment]
As a side note, @chillu or @tractorcow or anybody that can help. I'm happy to pay for a quick screen sharing/pairing session to get this working or at the very least identify where it's breaking.

**Comment by trev** [comment]
If it helps at all, I'm running SS 3.1.18 with silverstripe/behat-extension (1.0.1) and silverstripe/testsession (0.2.0)

**Comment by dhensby** [comment]
Hey @trev sorry for the silence on this - these problems as usually notoriously difficult for us to debug remotely/through GH issues.

I've only recently got behat tests running on a local VM to test a few things and didn't experience a problem like this.

Are you using an `_ss_environment.php` file? What's your setup/host machine?

**Comment by trev** [comment]
Hey @dhensby thanks for getting back to me. I was starting to despair :)

I'm running Behat in a Vagrant/Virtualbox VM running Ubuntu 14.04LTS on a standard LAMP stack.

My `_ss_environment.php` is quite simple and looks like this:
    
    <?php
    global $_file_to_url_mapping;
    $_file_to_url_mapping['/var/www/mysites.dev'] = 'http://mysites.dev';

As mentioned above, I'm a happy to provide a bounty and share screen to get this issue resolved... if it helps and it's something you're happy to do.

**Comment by dhensby** [comment]
@trev OK, you're environment file is either not being included or it is part of the problem.

The environment file has to have some constants defined that you don't have otherwise SS will throw an error at you.

Can you define your DB credentials in your environment file and see if that makes a difference? I'm not sure but perhaps the behat extension is looking for the constants that should be defined (and not finding them) and so producing an incomplete dbDetails array.

**Comment by trev** [comment]
Hi @dhensby, thanks for your help. I'm off on holidays now but it will be the first thing I do when I get back. I'll keep you posted. Thanks again for taking the time to assist me with this.

**Comment by tractorcow** [comment]
This sounds like a bug in testsession. It should probably work with database configs defined in _mysite.php as well as _ss_environment.php.

@trev how are you declaring your connection details? please post.

**Comment by trev** [comment]
@dhensby @tractorcow I've finally figured it out. All I needed was a holiday to refresh the mind. Damian was right: it's a testsession issue... kind of.

Basically our main project folder was called: `xellent`. As you know Silverstripe by default loads modules in alphabetical order. `xellent` module is where the database config is handled.

Since `testsession` was therefore loading before `xellent` the `$databaseConfig` was still blank.

What I don't understand (I haven't yet looked through that part of code) is why the `testsession` module was able to create the temp database since it would have needed the `$databaseConfig`... I'm guessing it's because when the temp DB is created it's called at a point where all the modules are loaded already.

Anyway, if I change the project folder to start with any letter before `t` it works.

**Comment by dhensby** [comment]
thanks for updating us @trev - this is a core issue that would be good to fix.. some way to get the module folders loaded in some particular order :/
