### ISSUE TITLE
Manually include composer autoload

### ISSUE THREAD

**Issue by dhensby** [silverstripe-labs/silverstripe-behat-extension#116]
At the moment the autoloader is included by framework inside `framework/core/Core.php`

This poses problems when we need to include composer managed packages before `Core.php` is included. I've addressed this issue here https://github.com/silverstripe/silverstripe-framework/pull/5572 by moving the autoloader include to as early in the execution as possible. 

To get the behat tests passing we need to include the autoloader as early as early as possible in the behat bootstrap. 

This problem was solved for PHPUnit by adding the include to the `cli-script.php` in core and I expect there's a similar file we can do this in for this module.

**Comment by sminnee** [comment]
This might be relevant: http://stackoverflow.com/questions/28852162/how-to-require-vendor-autoload-php-with-behat-yml

**Comment by dhensby** [comment]
> Composer's autoloader is used by default.

Yep, looks like a red herring
