### ISSUE TITLE
BasicContext::iWaitUntilISeeText won't find visible text on a page if there's an invisible version earlier

### ISSUE THREAD

**Issue by tim-mediasuite** [silverstripe-labs/silverstripe-behat-extension#209]
https://github.com/silverstripe/silverstripe-behat-extension/blob/4/src/Context/BasicContext.php#L1149

I'm reading this as, effectively,

1. find the first element on the page containing $text
2. return true/false depending on if the element is visible

But if there's another visible version of the text on the page, it'll never be found.

(This came up with tests on the CMS admin where test text ended up in a hidden field - this meant that the visible text was never found)

I have a patch for this that does 'check every element containing $text and return true if at least one is visible' but I thought I'd check whether this is a sensible change first before I do a PR - obviously this might affect a lot of existing tests.

**Comment by dhensby** [comment]
Fixing this makes sense to me, but it's hard to know the impact without seeing some test suites run with the change.

If you have done the patch and opening a PR is relatively trivial for you, I think that would be good to do so we can see the impact.

**Comment by emteknetnz** [comment]
Unlikely to have to much impact on existing tests IMO, so PR makes sense

Opening a PR on behat extension won't reveal the impact because all the core behat tests on things like asset-admin won't be run by the PR.  It's ok, I think we should do this and I can fix up any regressed tests later

**Comment by tim-mediasuite** [comment]
I've tested this against our existing suite that was testing a CMS admin page.

**Comment by emteknetnz** [comment]
Great ta, I've released as a new minor [4.9.0](https://github.com/silverstripe/silverstripe-behat-extension/releases/tag/4.9.0) due to it technically being a behavioral change

**Comment by tim-mediasuite** [comment]
Looks good, cheers.
