### ISSUE TITLE
Review behat tests to avoid using admin users

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe-labs/silverstripe-behat-extension#220]
A lot of our behat tests are using users with full admin privileges. This may be obfuscating bugs where a regular users ought to be able to perform some actions.

List of Behat tests : https://docs.google.com/spreadsheets/d/1wWJ2sBcFzPrTbaChxZd6rLKqSGxsLou4cif5WKuj7zc/edit?usp=sharing

## Acceptance criteria
- [x] Review all supported modules with Behat test and update test to use non-admin users where possible
- [x] Fix all failures or create follow up cards
- [ ] Apply fixes to CMS4 and merge up to CMS 5

## Related card
- https://github.com/silverstripe/silverstripe-assets/issues/501

### Behat tests
- [x] https://github.com/silverstripe/silverstripe-elemental/pull/1005
- [x] https://github.com/dnadesign/silverstripe-elemental-userforms/pull/64
- [x] https://github.com/silverstripe/silverstripe-campaign-admin/pull/241
- [x] https://github.com/silverstripe/silverstripe-elemental-bannerblock/pull/92
- [x] https://github.com/silverstripe/silverstripe-elemental-fileblock/pull/32
- [x] https://github.com/silverstripe/silverstripe-sitewidecontent-report/pull/54
- [x] https://github.com/silverstripe/silverstripe-subsites/pull/487
- [x] https://github.com/silverstripe/silverstripe-versioned-admin/pull/252
- [x] https://github.com/silverstripe/silverstripe-taxonomy/pull/84
- [x] https://github.com/silverstripe/silverstripe-totp-authenticator/pull/99
- [x] https://github.com/silverstripe/silverstripe-session-manager/pull/121
- [x] https://github.com/silverstripe/silverstripe-cms/pull/2777
- [x] https://github.com/silverstripe/silverstripe-siteconfig/pull/126
- [x] https://github.com/silverstripe/silverstripe-blog/pull/687
#### Blocked by supporting enhancement 
- [x] https://github.com/silverstripe/silverstripe-admin/pull/1356
- [x] https://github.com/silverstripe/silverstripe-asset-admin/pull/1292
#### Blocked by other issues
- [ ] https://github.com/silverstripe/silverstripe-ckan-registry/pull/275
- [ ] https://github.com/silverstripe/silverstripe-externallinks/pull/84
### Required additional investigation and enchantment
- [x] https://github.com/silverstripe/silverstripe-userforms/pull/1169

### Supporting enhancement
- [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/120
- [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/223
- [x] https://github.com/silverstripe/silverstripe-frameworktest/pull/122

**Comment by sabina-talipova** [comment]
List of modules, running behat tests with ADMIN permissions:
- [x] silverstripe-elemental
- [x] silverstripe-elemental-userforms
- [x] admin
- [x] asset-admin
- [x] blog
- [x] campaign-admin
- [x] ckan-registry
- [x] cms
- [x] contentreview
- [x] elemental-bannerblock
- [x] elemental-fileblock
- [x] externallinks
- [x] mfa
- [x] securityreport
- [x] session-manager
- [x] sharedraftcontent
- [x] siteconfig
- [x] sitewidecontent-report
- [x] subsites
- [x] taxonomy
- [x] totp-authenticator
- [x] userforms
- [x] versioned-admin

**Comment by sabina-talipova** [comment]
List of test cases: https://docs.google.com/spreadsheets/d/1wWJ2sBcFzPrTbaChxZd6rLKqSGxsLou4cif5WKuj7zc/edit#gid=0

**Comment by sabina-talipova** [comment]
I removed PR https://github.com/silverstripe/silverstripe-contentreview/pull/172 from this task and append it to https://github.com/silverstripe/silverstripe-contentreview/pull/155, because it is more related to `silverstripe-contentreview` PR

**Comment by GuySartorelli** [comment]
PRs are all merged.
