### ISSUE TITLE
TODO: FixtureContext::stepCreateRecordWithTable - Support more than one record

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe-labs/silverstripe-behat-extension#253]
## Description
FixtureContext::stepCreateRecordWithTable - Support more than one record

See: 
https://github.com/silverstripe/silverstripe-behat-extension/blob/22220299bd3dd46444cff3834dc0b498fbedc07c/src/Context/FixtureContext.php#L302

**Comment by GuySartorelli** [comment]
Gonna close this - it's easy enough to just have a separate table for each record.
