### ISSUE TITLE
TODO: FixtureContext::stepThereAreTheFollowingRecords - Run prepareAsset() for each File and Folder record

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe-labs/silverstripe-behat-extension#254]
## Description
FixtureContext::stepThereAreTheFollowingRecords - Run prepareAsset() for each File and Folder record

See: 
https://github.com/silverstripe/silverstripe-behat-extension/blob/22220299bd3dd46444cff3834dc0b498fbedc07c/src/Context/FixtureContext.php#L525

**Comment by GuySartorelli** [comment]
Gonna close this - if we haven't needed it until now, we probably just don't need it.
