### ISSUE TITLE
Behat extension fails to install

### ISSUE THREAD

**Issue by Jinelle** [silverstripe-labs/silverstripe-behat-extension#86]
Hi,

I had issues when trying to install the Behat extension.

EXAMPLE PC:/var/www/html/silverstripe$ composer create-project silverstripe/installer .

EXAMPLE-PC:/var/www/html/silverstripe$ composer require "silverstripe/behat-extension:*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - silverstripe/behat-extension dev-webservice-tutorial requires behat/mink 1.6.*-dev -> no matching package found.
    - silverstripe/behat-extension dev-experiments/behat-3-upgrade requires phpunit/phpunit 4.*@stable -> no matching package found.
    - silverstripe/behat-extension dev-develop requires behat/mink 1.6.*-dev -> no matching package found.
    - silverstripe/behat-extension 0.1.x-dev requires phpunit/phpunit 3.7.x-dev -> no matching package found.
    - Installation request for silverstripe/behat-extension * -> satisfiable by silverstripe/behat-extension[0.1.x-dev, dev-develop, dev-experiments/behat-3-upgrade, dev-master, dev-webservice-tutorial].
    - Conclusion: remove symfony/yaml 2.8.x-dev
    - Conclusion: don't install symfony/yaml 2.8.x-dev
    - silverstripe/behat-extension dev-master requires symfony/yaml 2.6.*@stable -> satisfiable by symfony/yaml[2.6.x-dev, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7].
    - Can only install one of: symfony/yaml[2.6.x-dev, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.0, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.0-BETA1, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.0-BETA2, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.1, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.2, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.3, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.4, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.5, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.6, 2.8.x-dev].
    - Can only install one of: symfony/yaml[v2.6.7, 2.8.x-dev].
    - Installation request for symfony/yaml == 2.8.9999999.9999999-dev -> satisfiable by symfony/yaml[2.8.x-dev].

Cheers,
Jinelle

**Comment by jeffreyguo** [comment]
Hi Jinelle,
Could you try this? 
```Switch to the newly created webroot, and add the SilverStripe Behat extension.

cd my-test-project
composer require "silverstripe/behat-extension:*"
```

**Comment by chillu** [comment]
Sorry for the delay, Jinelle! This happened because the first installer command includes `phpunit/phpunit`, which requires `symfony/yaml:~2.0`. That used to resolve to `2.6` and matched the stricter dependencies in the behat extension (`2.6.x@stable`). But since then `2.7` and `2.8` came out, breaking composer. Really, composer should deal with this situation more gracefully, but what can I say ... dependency hell. How are you going otherwise with SilverStripe and Behat?
